[mypy]
python_version = 3.13
strict = True
warn_unreachable = True
warn_redundant_casts = True
warn_unused_ignores = True
disallow_any_generics = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True
no_implicit_reexport = True
warn_return_any = True
show_error_codes = True
namespace_packages = True
explicit_package_bases = True
mypy_path = src

[mypy-duckdb.*]
ignore_missing_imports = True

[mypy-asyncmy.*]
ignore_missing_imports = True

[mypy-aiosqlite.*]
ignore_missing_imports = True

[mypy-asyncpg.*]
ignore_missing_imports = True

[mypy-structlog.*]
ignore_missing_imports = True

[mypy-textual.*]
ignore_missing_imports = True

[mypy-rapidfuzz.*]
ignore_missing_imports = True

[mypy-tests.*]
disallow_untyped_defs = False
